name = "havenapi"
bin = "bin/havenapi"
vcs = ""
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = true
as_api = false
